# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 656e7807dd85883894fbf52c92d3d2d008bdaea2a66f1f9879eb09458c55847a98fb4dbdfe77e32766ed97a0663108c9bbac21367a69cc1b9e679235cfbdc7a1

test:
  secret_key_base: fb05f27429f1806121e5abb39a8fb01e83d418e14ca65fab1787f099f18048414a6393ec6f53f8f0719e1d011fe6c992042c3a06d18557703b3d06144885f820

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
